class_name Constants



enum TileType {NONE, FIELD, FOREST, MOUNTAIN, CLOUD, UNIT, SHORES, OCEAN}
enum Tribe {IMP}
enum Asset {SELECTION, FIELD, FOREST, MOUNTAIN, FRUIT, ANIMAL, CROP, 
	METAL, CLOUD, WARRIOR, BLANK, MOVETARGET, ZOC1MOVETARGET, ZOC2MOVETARGET, ROAD, HOLD, HOLD2, SHORES, OCEAN, RUIN, VILLAGE} 
enum UnitType {NONE, WARRIOR}
enum BuildingType {NONE, ROAD, RUIN, VILLAGE}
enum Player {ONE, TWO, THREE, FOUR, FIVE, SIX}
